services:
  meistrocraft:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount persistent directories
      - ./projects:/app/projects
      - ./sessions:/app/sessions
      - ./persistent_memory:/app/persistent_memory
      - ./token_usage:/app/token_usage
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development service with hot reload
  meistrocraft-dev:
    build: .
    ports:
      - "8001:8000"
    volumes:
      # Mount source code for development
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
    command: ["python3", "-m", "uvicorn", "web_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev